# Generated by Django 4.2.2 on 2023-07-06 21:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('duration', models.PositiveBigIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=40)),
                ('credits', models.PositiveBigIntegerField()),
                ('professor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('first_last_name', models.CharField(max_length=35)),
                ('second_last_name', models.CharField(max_length=35)),
                ('first_name', models.CharField(max_length=35)),
                ('middle_name', models.CharField(max_length=35)),
                ('date_of_birth', models.DateField()),
                ('genre', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1)),
                ('validity', models.BooleanField(default=True)),
                ('carrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.carrer')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.student')),
            ],
        ),
    ]
